### ISSUE TITLE
Add MSGEQ7 support for "christmas tree"

### ISSUE THREAD

**Issue by marksev1** [jakeloggins/Clod-sketch-library#1]
For music sychronized "light-show". I think its a good addition :).

**Comment by jakeloggins** [comment]
Here's an initial attempt at supporting it:
https://github.com/jakeloggins/Clod-sketch-library/tree/master/sketches/christmas_tree_MSGEQ7

I don't have that chip, so you'll have to test it and let me know if it works. If you toggle the playFromMSGEQ7 endpoint to false, the sketch will work as the other one does normally. If you set it to true, it will do nothing but respond to the MSGEQ7 until you toggle it back to false.

Just set up Clod and upload that sketch onto the chip. Chat with me in gitter if you have any trouble.

**Comment by marksev1** [comment]
Nice.. Waiting for the chip to arrive from China. Gonna ping you when I'm ready to roll, should I close the issue in the meantime?

**Comment by jakeloggins** [comment]
Ok that's fine. Just leave the issue open because there's almost no chance I got the code right on the first try.

**Comment by marksev1** [comment]
I'll let you know when I get to this jakeloggins :).
